version: '3'

services:
  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.6
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  # Define a Chronograf service
  chronograf:
    image: chronograf:1.5
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
      - "8888:8888"
    links:
      - influxdb

  # Define NATS
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
